# Generated by Django 2.1 on 2019-06-26 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='ps',
            field=models.CharField(max_length=30, null=True, verbose_name='P.S.'),
        ),
    ]
